### ISSUE TITLE
Названи_ца проекта не соответствует_ница

### ISSUE THREAD

**Issue by plaxeen** [envrm/feminizator#3]
Феминизатор — слово мужского рода! Срочно заменить, оно не уважает женщин.

феминизатор ⚧ ка | феминизатор ⚧ иха | феминизатор ⚧ иня | феминизатор ⚧ киня | феминизатор ⚧ есса | феминизатор ⚧ ица

**Comment by envrm** [comment]
Всё-таки я это сделал. Теперь по клику на заголовке добавляется суффикс.
