### ISSUE TITLE
лилипут, житель

### ISSUE THREAD

**Issue by makc** [envrm/feminizator#6]
"лилипутка" есть в wiktionary, гуглопереводчик её знает, народ пользуется хоть и не активно:
![screen shot 2019-02-14 at 21 59 38](https://user-images.githubusercontent.com/242577/52817399-051bf980-30a4-11e9-8426-b20cb0c381c7.png)
в то же время феминизатор лилипутов не феминизирует:
![screen shot 2019-02-14 at 21 58 28](https://user-images.githubusercontent.com/242577/52817424-195ff680-30a4-11e9-82f5-c747e693ed2d.png)
алсо, почему он предлагает жител_ессу вместо жительницы?

**Comment by feminizator** [comment]
Суффикс -ут добавил. Жительница есть, но кроме неё есть и другие формы, которые в дефиницию подставляются случайно (они меняются при повторных запросах).

Формы не странные, всё по канону:
![Болотина](https://pp.userapi.com/c623117/v623117539/35f09/_zVQCpq3as8.jpg)
